[package]
name = "tohdr-cli"
version = "0.1.0"
description = "tohdr command-line interface"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "tohdr"
path = "src/main.rs"

[dependencies]
tohdr-core.workspace = true
tohdr-heif.workspace = true
tohdr-apple.workspace = true
tohdr-portable.workspace = true
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
